
default:all

all:atoi longest_common_prefix count_and_say pretty_json integer_to_roman multiply_strings

atoi:atoi.c
	gcc atoi.c -o atoi

longest_common_prefix: longest_common_prefix.c
	gcc longest_common_prefix.c -o longest_common_prefix

count_and_say: count_and_say.c
	gcc count_and_say.c -o count_and_say

pretty_json: pretty_json.c
	gcc pretty_json.c -o pretty_json

integer_to_roman: integer_to_roman.c
	gcc integer_to_roman.c -o integer_to_roman

multiply_strings: multiply_strings.c
	gcc -g multiply_strings.c -o multiply_strings

clean:
	rm atoi longest_common_prefix count_and_say pretty_json integer_to_roman multiply_strings
