
default:all

all: stack_test_array stack_test_LL evaluate_expression

stack_test_LL:stack_test_LL.c

	gcc stack_test_LL.c -o stack_test_LL

stack_test_array:stack_test_array.c

	gcc stack_test_array.c -o stack_test_array

clean:
	rm stack_test_LL stack_test_array 
